name: Unit Tests
on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-noble
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/actions/setup-node-env@main

      - name: Build
        run: npm run-script build

      - name: Run Eslint
        run: npm run-script lint

      - name: Run unit tests
        run: npm run-script test

      - name: Run visual regression tests on PR
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: npm run-script test:visual
