name: Update Screenshots

on:
  workflow_call:

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-noble
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/actions/setup-node-env@main

      - name: Run visual regression tests
        run: npm run test:visual
        id: tests
        continue-on-error: true

      - name: Update screenshots
        if: ${{ steps.tests.outcome == 'failure' }}
        run: |
          npm run test:update
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add screenshots
          git commit -m "test: update screenshots"
          git push
